version: '3.8'
services:
  demo:
    # image: ghcr.io/open-feature/open-feature-demo:latest
    build: .
    ports:
      - '30000:30000'
    command:
      - flagd
    depends_on:
      - flagd
      - jaeger
    volumes:
      - ${PWD}/config/flagd/flags.json:/opt/playground/config/flagd/flags.json
      - flagd-socket:/tmp/
    environment:
     - FLAGD_SOCKET_PATH=/tmp/flagd-socket
     - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
     - OTEL_EXPORTER_JAEGER_AGENT_PORT=6832
     - GO_FEATURE_FLAG_URL=http://go-feature-flag:1031
      # Set from the .env file
     - HARNESS_KEY
     - SPLIT_KEY
     - CLOUDBEES_APP_KEY

  jaeger:
    image: jaegertracing/all-in-one:1.38
    ports:
     - "6832:6832/udp"
     - "16686:16686"

  flagd:
    image: ghcr.io/open-feature/flagd:v0.2.1
    command:
      - start
      - --uri
      - /etc/flagd/flags.json
      - --socket-path
      - /tmp/flagd-socket
    volumes:
      - ${PWD}/config/flagd/flags.json:/etc/flagd/flags.json
      - flagd-socket:/tmp/
    ports:
      - '8013:8013'

  go-feature-flag:
    image: thomaspoignant/go-feature-flag-relay-proxy:v0.3.0
    volumes:
      - ${PWD}/config/go-feature-flag:/goff/
    ports:
      - '1031:1031'

volumes:
  flagd-flags:
  flagd-socket:
