# Go Feature Flag Relay Proxy
#
# Additional information and configuration options can be found here:
# https://github.com/thomaspoignant/go-feature-flag-relay-proxy

listen: 1031
pollingInterval: 1000
startWithRetrieverError: false
retriever:
  kind: file
  path: /goff/flags.yaml
exporter:
  kind: log
